### ISSUE TITLE
leader service && validator service crashed by  "cannot allocate memory" 

### ISSUE THREAD

**Issue by luhuimao** [bitconch/bitconch-core#124]
Call stack:
thread 'soros-banking-stage-tx' panicked at 'failed to map the data file: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
[2019-07-28T22:05:06.103709155Z INFO  soros::broadcast_stage] broadcast: 1 entries, blob time 0 broadcast time 0
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: soros_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:482
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   7: rust_begin_unwind
             at src/libstd/panicking.rs:312
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::result::unwrap_failed
  10: soros_runtime::append_vec::AppendVec::new
  11: soros_runtime::accounts_db::AccountsDB::store
  12: soros_runtime::accounts::Accounts::store_accounts
  13: soros_runtime::bank::Bank::commit_transactions
  14: soros::banking_stage::BankingStage::process_and_record_transactions
  15: soros::banking_stage::BankingStage::process_received_packets
  16: soros::banking_stage::BankingStage::process_packets
  17: soros::banking_stage::BankingStage::process_loop

Hit this issue when trying to map a file to the memory:

 //UNSAFE: Required to create a Mmap
 let map = unsafe { MmapMut::map_mut(&data).expect("failed to map the data file") };

**Comment by luhuimao** [comment]
Adding following codes in  runtime/src/append_vec.rs to fix the issue:
        if create {
            let _ignored = remove_file(file);
            if let Some(parent) = file.parent() {
                create_dir_all(parent).expect("Create directory failed");
            }
        }

        let mut data = OpenOptions::new()
            .read(true)
            .write(true)
            .create(create)
            .open(file)
            .map_err(|e| {
                let mut msg = format!("in current dir {:?}\n", std::env::current_dir());
                for ancestor in file.ancestors() {
                    msg.push_str(&format!(
                        "{:?} is {:?}\n",
                        ancestor,
                        std::fs::metadata(ancestor)
                    ));
                }
                panic!(
                    "{}Unable to {} data file {}, err {:?}",
                    msg,
                    if create { "create" } else { "open" },
                    file.display(),
                    e
                );
            })
            .unwrap();

**Comment by luhuimao** [comment]
Compile and start the services see if hit this issue again.

**Comment by luhuimao** [comment]
Still hit the same issue and crashed.
